name: Run bug in progress

on:
  repository_dispatch:
    types:
      - decaf_bug_in_progress

jobs:
  create-branch:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create branch
        env:
          BRANCH_NAME: ${{ github.event.client_payload.branch }}
        run: |
          echo "Creating branch: $BRANCH_NAME"

          git checkout -b "$BRANCH_NAME"

          git push origin "$BRANCH_NAME"
