name: Build Reusable Workflow

on:
  workflow_dispatch: # on button click
  push:
    branches: [ master, main ]
    paths:
      - src/**
      - tests/**
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [20, 22]  # Add your desired versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
    
      # Cache dependencies (npm)
      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.node-version }}-

      # Install dependencies only if cache missed
      - run: npm ci

      # Cache build outputs (e.g., dist/)
      - name: Cache build artifacts
        id: cache-build
        uses: actions/cache@v4
        with:
          path: dist  # Replace with your build output directory
          key: build-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('src/**', 'package.json') }}
          restore-keys: |
            build-${{ runner.os }}-${{ matrix.node-version }}-
    

      # Run build only if dependencies changed or build cache missed
      - if: steps.cache-npm.outputs.cache-hit != 'true' || steps.cache-build.outputs.cache-hit != 'true'
        run: npm run build:prod  # Replace with your build command