name: "Build & Test"

on:
  workflow_dispatch: # on button click
  push:
    branches: [ master, main ]
    paths:
      - src/**
      - tests/**
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    strategy:
      matrix:
        node-version: [20, 22]  # Add your desired versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      # Cache dependencies (npm)
      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.node-version }}-

      # Install dependencies only
      - run: npm ci

      - run: npm run build:prod  # Replace with your build command      

      - run: npm run test:all