name: "Pages Builder"

on:
  workflow_dispatch: # on button click
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
    branches: [ master, main ]
    paths:
      - workdocs/**
      - .github/workflows/pages.yaml

jobs:
  # Single deploy job no building
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    strategy:
      matrix:
        node-version: [ 20, 22 ]
    environment:
      name: github-pages
    #      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.node-version }}-

      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: dist
          key: build-${{ runner.os }}-${{ hashFiles('src/**', 'package.json') }}
          restore-keys: |
            build-${{ runner.os }}-${{ matrix.node-version }}-
      - run: npm run coverage
      - run: npm run docs
      - name: Setup Pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: docs
          path: docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: docs
